version: '3'

# Gitea - git server written in Golang

services:

  gitea:
    image: gitea/gitea:latest
    ports:
      - 3000:3000
      - 22:22
    restart: always
    volumes:
      - ./data/gitea:/data
    depends_on:
      - db
  db:
    image: mariadb:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=changeme
      - MYSQL_DATABASE=gitea
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=changeme
    volumes:
      - ./data/db:/var/lib/mysql
