# version: '3'
version: '3.5'

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: always
    ports:
      - 80:80
      - 443:443
    command: --docker # Tells Træfik to listen to docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
      - ./data:/data
    labels:
      - traefik.enable=false
    networks:
      - lbclients


networks:
  lbclients:
    external:
      name: loadbalancer
