version: '3.5'

# still in progress - seeing errors during startup, need to get solr and redis working properly, 
# among other things

networks:
  backend:

services:
  nextcloud:
    image: benyanke/nextcloud:latest
    restart: always
    ports:
      - 8888
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - traefik.enable=true
      # TODO: Update your domain here
      - traefik.backend=example.com
      - traefik.frontend.rule=Host:example.com
      - traefik.backend.healthcheck.hostname=example.com
      - traefik.docker.network=proxy
      - traefik.port=8888
    links:
      - db           # If using MySQL
      - collabora    # If using document server
#      - solr                   # If using Nextant
#      - redis                  # If using Redis
    environment:
      - ADMIN_USER=admin            # Don't set to configure through browser
      - ADMIN_PASSWORD=admin        # Don't set to configure through browser
      - DOMAIN=10.10.10.10

      # Probably don't need to adjust below here
      - UID=1000
      - GID=1000
      - UPLOAD_MAX_SIZE=100G
      - APC_SHM_SIZE=128M
      - OPCACHE_MEM_SIZE=128
      - CRON_PERIOD=5m
      - TZ=America/Chicago
      - DB_TYPE=mysql
      # If you change this, adjust below in 'db' container too
      - DB_NAME=nextcloud
      - DB_USER=nextcloud
      - DB_PASSWORD=supersecretpassword
      - DB_HOST=db
    volumes:
      - ./data/data:/data
      - ./data/config:/config
      - ./data/apps:/apps2
      - ./data/themes:/nextcloud/themes
    networks:
      - backend

  # If using MySQL
  db:
    image: mariadb:latest
    restart: always
    networks:
      - backend
    volumes:
      - ./data/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=supersecretpassword
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=supersecretpassword

  # If using Nextant
#  solr:
#    image: solr:7-alpine
#    container_name: solr
#    volumes:
#      - ./data/solr:/opt/solr/server/solr/mycores
#    entrypoint:
#      - docker-entrypoint.sh
#      - solr-precreate
#      - nextant

  # If using Nextant
  docs:
    image: onlyoffice/documentserver:latest
    restart: always
    ports:
      - 80
#    environment:
      # update this with your NC domain
#      - DOMAIN=example.com 
    volumes:
      - ./data/docs/logs:/var/log/onlyoffice
      - ./data/docs/certs:/var/www/onlyoffice/Data
      - ./data/docs/cache:/var/lib/onlyoffice
      - ./data/docs/db:/var/lib/postgresql
    networks:
      - backend

# TODO: Look at seperate redis, postgres for this. Maybe another whole stack.

  # If using Redis
  redis:
    image: redis:alpine
    restart: always
    volumes:
      - ./data/redis:/data
    networks:
      - backend
