version: '3.5'

# Passbolt - web based password manager

networks:
  backend:

services:
  passbolt:
    image: passbolt/passbolt:latest
    restart: always
    ports:
      - 80
    links:
      - db           # If using MySQL
#      - solr                   # If using Nextant
#      - redis                  # If using Redis
    environment:
      - DATASOURCES_DEFAULT_HOST=db
      - DATASOURCES_DEFAULT_PASSWORD=supersecretpassword
      - DATASOURCES_DEFAULT_USERNAME=passbolt
      - DATASOURCES_DEFAULT_DATABASE=passbolt
      - APP_FULL_BASE_URL=https://example.com
    volumes:
      - ./data/data:/data
    networks:
      - backend

  db:
    image: mariadb:latest
    restart: always
    networks:
      - backend
    volumes:
      - ./data/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=supersecretpassword
      - MYSQL_DATABASE=passbolt
      - MYSQL_USER=passbolt
      - MYSQL_PASSWORD=supersecretpassword
