version: '3'

# Still in progress

services:

  ldap:

    # Use me for released version
    image: glauth/glauth:latest

    # Use me for dev branch / unstable version
    # image: glauth/glauth:develop

    ports:
     - 389:389
     - 636:636

    volumes:
     - ./data/:/app/config/
