version: '3'

# Unifi Controller - Ubiquity access point centralized controller
# Still in progress

services:
  unifictrl:
    image: linuxserver/unifi:latest
    restart: always
    ports:
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 8081:8081
      - 8443:8443
      - 8843:8843
      - 8880:8880
      - 6789:6789
    volumes:
      - ./data/config:/config
